mod: cosmetic

diff --git a/.local/bin/acw b/.local/bin/acw
--- a/.local/bin/acw
+++ b/.local/bin/acw
@@ -2,11 +2,11 @@
 
 if ! command -v w3m &> /dev/null; then
 	echo "Error: 'w3m' not found"
-	return 1
+	exit 1
 fi
 if [ $# -ne 2 ]; then
-	echo -e "Error: Invalid argument.\nUsage: acw abc290 a"
-	return 1
+	echo -e "Error: Invalid argument.\nUsage: 'acw abc290 a'"
+	exit 1
 fi
 
 sed_str="s/\\\\leq/<=/g;"
diff --git a/.local/bin/cpp-submit b/.local/bin/cpp-submit
--- a/.local/bin/cpp-submit
+++ b/.local/bin/cpp-submit
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$#" -ne 1 ]; then
-	echo -e "Error: Invalid argument.\nUsage: cpp-submit main.cpp"
-	return 1
+	echo -e "Error: Invalid argument.\nUsage: 'cpp-submit main.cpp'"
+	exit 1
 fi
 
 cpp-test "$1" && acc submit "$1"
diff --git a/.local/bin/cpp-test b/.local/bin/cpp-test
--- a/.local/bin/cpp-test
+++ b/.local/bin/cpp-test
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$#" -ne 1 ]; then
-	echo -e "Error: Invalid argument.\nUsage: cpp-test main.cpp"
-	return 1
+	echo -e "Error: Invalid argument.\nUsage: 'cpp-test main.cpp'"
+	exit 1
 fi
 
 cpl "$1" && oj test --directory "tests/" && command rm ./a.out
