add: modify voltage with `cpuset`

diff --git a/.local/bin/cpuset b/.local/bin/cpuset
--- a/.local/bin/cpuset
+++ b/.local/bin/cpuset
@@ -20,23 +20,47 @@ case "$action" in
 		cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | uniq
 		;;
 	max)
-		sudo -A cpupower frequency-set -u 5GHz > /dev/null
+		sudo cpupower frequency-set -u 5GHz > /dev/null
 		;;
 	high)
-		sudo -A cpupower frequency-set -u 4GHz > /dev/null
+		sudo cpupower frequency-set -u 4GHz > /dev/null
 		;;
 	middle)
-		sudo -A cpupower frequency-set -u 2.5GHz > /dev/null
+		sudo cpupower frequency-set -u 2.5GHz > /dev/null
 		;;
 	low)
-		sudo -A cpupower frequency-set -u 1.5GHz > /dev/null
+		sudo cpupower frequency-set -u 1.5GHz > /dev/null
 		;;
 	min)
-		sudo -A cpupower frequency-set -u 1GHz > /dev/null
+		sudo cpupower frequency-set -u 1GHz > /dev/null
+		;;
+	volt)
+		level=$2
+		case $level in
+			low)
+				volt=5000
+				temp=50
+				sudo ryzenadj --stapm-limit=$volt --fast-limit=$volt --slow-limit=$volt --tctl-temp=$temp --power-saving
+				;;
+			middle)
+				volt=10000
+				temp=65
+				sudo ryzenadj --stapm-limit=$volt --fast-limit=$volt --slow-limit=$volt --tctl-temp=$temp --power-saving
+				;;
+			high)
+				volt=20000
+				temp=80
+				sudo ryzenadj --stapm-limit=$volt --fast-limit=$volt --slow-limit=$volt --tctl-temp=$temp --power-saving
+				;;
+			*)
+				echo "Invalid arguments:" 1>&2
+				echo "Usage: cpuset volt {low, middle, high}" 1>&2
+				;;
+		esac
 		;;
 	*)
 		echo "Invalid option: $action" 1>&2
-		echo "Usage: cpuset {max, high, middle, low, min}" 1>&2
+		echo "Usage: cpuset {min, low, middle, high, max}" 1>&2
 		exit 1
 		;;
 esac
