mod: cosmetic

diff --git a/.local/bin/python-submit b/.local/bin/python-submit
--- a/.local/bin/python-submit
+++ b/.local/bin/python-submit
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$#" -ne 1 ]; then
-	echo -e "Error: Invalid argument.\nUsage: python-submit main.py"
-	return 1
+	echo -e "Error: Invalid argument.\nUsage: 'python-submit main.py'"
+	exit 1
 fi
 
 python-test "$1" && acc submit "$1" -- --language 5055
diff --git a/.local/bin/python-test b/.local/bin/python-test
--- a/.local/bin/python-test
+++ b/.local/bin/python-test
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$#" -ne 1 ]; then
-	echo -e "Error: Invalid argument.\nUsage: python-test main.py"
-	return 1
+	echo -e "Error: Invalid argument.\nUsage: 'python-test main.py'"
+	exit 1
 fi
 
 oj test --directory "tests/" -c "python3 $1"
